version: '3'

services:
  mysql:
    image: 'mysql:8'
    container_name: 'java-mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: 'jwtapptest'
  jwtapptest:
    build: ./
    container_name: 'jwtapptest'
    ports:
    - "8075:8075"
    links:
      - mysql:localhost